## Sample Data

* Dataset akan digenerate sebagai numpy array, maka perlu mengimport numpy
* Mengimport modul prepeocessing dari sklearn
* Dataset yang akan di buat terdiri dari 4 baris, yang mana setiap baris memiliki 3 features
* Dataset akan di tampung oleh sample_data

In [1]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1, -1.9, 5.5], 
                        [-1.5, 2.4, 3.5], 
                        [0.5, -7.9, 5.6], 
                        [5.9, 2.3, -5.8]])
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

* Pemanggilan sample_data.shape dilakukan untuk menampilkan dimensi dari dataset sample_data yang akan menghasilkan (3, 4) dimana dataset tersebut memiliki 4 baris dan 3 kolom atau features

In [2]:
sample_data.shape

(4, 3)

## Binarisation

Binarisation bertujuan untuk menghasilkan suatu data yang terdiri dari 2 numerik saja 0 dan 1.

In [3]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

Dataset sample_data memiliki nilai floating_point yang beragam. pada kali ini kita di minta untuk mengkonversi nilai pada sample_data menjadi 0 atau 1 dengan kondisi untuk setiap nilai yang lebih besar dari 0.5 akan dikonversi menjadi 1 dan untuk susanya akan dikonversikan jadi 0

In [4]:
preprocessor = preprocessing.Binarizer(threshold=0.5)
preprocessor
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

## Scaling

Teknik scaling bertujuan untuk menghasilkan data numerik yang berada dalam rentang skala tertentu

In [5]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

Dataset sample_data terdiri atas nilai floating point dengan rentang nilai -7.9 sampai dengan 5.9. Pada studi kasus kali ini, kita diminta untuk mengkonversi nilai numerik tersebut ke dalam rentang nilai 0 sampai dengan 1.

In [6]:
preprocessor = preprocessing.MinMaxScaler(feature_range=(0, 1))
preprocessor.fit(sample_data)
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

Kita juga dapat menyatukan proses fitting dan transform pada dataset yang sama secara sekaligus menggunakan fit_transform()

In [7]:
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

## L1 Normalization: Least Absolute Deviations

Teknik normalization bertujuan untuk melakukan normalisasi terhadap data numerik yang kita miliki

In [8]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

Memanggil preprocessing.normalize() yang disertai oleh 2 parameter.
* Parameter pertama adalah dataset yang akan dilakukan normalisasi.
* Parameter kedua adalah jenis normalisasi yang akan dikenakan ke dataset. Kali ini kita akan melakukan L1 Normalization, sehingga kita akan menentukan parameternya adalah norm='l1'.

In [9]:
l1_normalised_data = preprocessing.normalize(sample_data, norm='l1')
l1_normalised_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.42142857,  0.16428571, -0.41428571]])

## L2 Normalization: least Squares

In [10]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

Memanggil preprocessing.normalize() yang disertai oleh 2 parameter.
* Parameter pertama adalah dataset yang akan dilakukan normalisasi.
* Parameter kedua adalah jenis normalisasi yang akan dikenakan ke dataset. Kali ini kita akan melakukan L2 Normalization, sehingga kita akan menentukan parameternya adalah norm='l2'.

In [11]:
l2_normalised_data = preprocessing.normalize(sample_data, norm='l2')
l2_normalised_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.05156558, -0.81473612,  0.57753446],
       [ 0.68706914,  0.26784051, -0.6754239 ]])